# Generated by Django 4.2.1 on 2024-11-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('phrase', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dictionary/images')),
                ('voice', models.FileField(blank=True, null=True, upload_to='dictionary/audio')),
            ],
        ),
    ]
